/** @param {Record<string, unknown>} row */
export function rowToCar(row) {
  return {
    id: row.id,
    title: row.title,
    createdAt: new Date(row.created_at).getTime(),
    linkUrl: row.link_url ?? "",
    legalStatus: row.legal_status ?? "",
    electrical: row.electrical ?? "",
    rustWhere: row.rust_where ?? "",
    rustDegree: row.rust_degree ?? "",
    chipsWhere: row.chips_where ?? "",
    chipsDamage: row.chips_damage ?? "",
    damaged: row.damaged ?? "",
    dentsWhere: row.dents_where ?? "",
    dentsDamage: row.dents_damage ?? "",
    repaintWhere: row.repaint_where ?? "",
    repaintDegree: row.repaint_degree ?? "",
    color: row.color ?? "",
    generalCondition: row.general_condition ?? "",
    desc1: row.desc1 ?? "",
    desc2: row.desc2 ?? "",
    desc3: row.desc3 ?? "",
    listingStatus: row.listing_status ?? "listed",
    purchasePrice: row.purchase_price ?? "",
    salePrice: row.sale_price ?? "",
    investedAmount: row.invested_amount ?? "",
    vin: row.vin ?? "",
    mileage: row.mileage ?? null,
    status: row.status ?? "found",
    assignedTo: row.assigned_to ?? null,
    photos: Array.isArray(row.photos) ? row.photos : [],
    updatedAt: row.updated_at ? new Date(row.updated_at).getTime() : null,
  };
}

/** Карта полей JSON (camelCase) → колонки SQL */
export const PATCH_COLUMN_MAP = {
  title: "title",
  linkUrl: "link_url",
  legalStatus: "legal_status",
  electrical: "electrical",
  rustWhere: "rust_where",
  rustDegree: "rust_degree",
  chipsWhere: "chips_where",
  chipsDamage: "chips_damage",
  damaged: "damaged",
  dentsWhere: "dents_where",
  dentsDamage: "dents_damage",
  repaintWhere: "repaint_where",
  repaintDegree: "repaint_degree",
  color: "color",
  generalCondition: "general_condition",
  desc1: "desc1",
  desc2: "desc2",
  desc3: "desc3",
  listingStatus: "listing_status",
  purchasePrice: "purchase_price",
  salePrice: "sale_price",
  investedAmount: "invested_amount",
  vin: "vin",
  mileage: "mileage",
  status: "status",
  assignedTo: "assigned_to",
  photos: "photos",
};
